config:
  livereload: false
  minify_js: true
  sass:
    output_style: :compact
    source_maps: false
  dev_files:
    - dev/
    - modules.html
    - index.html
  dev_page_groups:
    - development
    - specs