config:
  livereload: true
  minify_js: false
  sass:
    output_style: :expanded
    source_maps: true
  dev_files:
    - "dev/"
    - "modules.html"
    - "index.html"
  dev_page_groups:
    - "development"
    - "specs"
  paths:
    layouts: "layouts/" #Relative to source
    partials: "partials/" #Relative to source
    modules: "modules/" #Relative to partials
    shared: "shared/" #Relative to partials
    assets:
      js: "assets/javascripts"
      css: "assets/stylesheets"
      fonts: "assets/fonts"
      images: "assets/images"
  ignore_files:
    - "assets/images/raw/*"
    - "assets/javascripts/development/*"
    - "assets/javascripts/dependencies/*"
    - "assets/stylesheets/partials/modules/*"
    - ".gitkeep"